BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/cma_da_aug_tune
CHECKPOINT_FOLDER: data/checkpoints/cma_da_aug_tune
EVAL_CKPT_PATH_DIR: data/checkpoints/cma_da_aug_tune

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 4
  batch_size: 5

  DAGGER:
    iterations: 10
    update_size: 5000
    p: 0.5
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/cma_da_aug_tune/trajectories.lmdb
    load_from_ckpt: True
    ckpt_to_load: data/checkpoints/cma_aug_tune/best_checkpoint.pth # REPLACE

MODEL:
  policy_name: CMAPolicy

  INSTRUCTION_ENCODER:
    bidirectional: True
