ENVIRONMENT:
  MAX_EPISODE_STEPS: 20

SIMULATOR:
  TYPE:
    Sim-v1
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: v0 # v1
  AGENT_0:
    SENSORS: [RGB_SENSOR, DEPTH_SENSOR]
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]

TASK:
  TYPE: VLN-v0
  # POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT, LOOK_UP, LOOK_DOWN]
  POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT, HIGHTOLOW]
  SUCCESS_DISTANCE: 3.0
  SENSORS: [
    RXR_INSTRUCTION_SENSOR, 
    SHORTEST_PATH_SENSOR, 
    VLN_ORACLE_PROGRESS_SENSOR
  ]
  INSTRUCTION_SENSOR_UUID: rxr_instruction

  MEASUREMENTS: [
    # STEPS_TAKEN,
    # PATH_LENGTH,
    # DISTANCE_TO_GOAL,
    # SUCCESS,
    # ORACLE_SUCCESS,
    # SPL,
    # NDTW,
    # TOP_DOWN_MAP_VLNCE
  ]
  #########################################
  # TOP_DOWN_MAP_VLNCE:
  #   DRAW_SHORTEST_PATH: False
  #   DRAW_REFERENCE_PATH: True
  #   DRAW_FIXED_WAYPOINTS: False
  #   DRAW_MP3D_AGENT_PATH: False
  #   FOG_OF_WAR:
  #     DRAW: True
  #     FOV: 360

  SUCCESS:
    SUCCESS_DISTANCE: 3.0
  SPL:
    SUCCESS_DISTANCE: 3.0
  NDTW:
    SUCCESS_DISTANCE: 3.0
    GT_PATH: data/datasets/RxR_VLNCE_v0/{split}/{split}_{role}_gt.json.gz
  SDTW:
    SUCCESS_DISTANCE: 3.0
    GT_PATH: data/datasets/RxR_VLNCE_v0/{split}/{split}_{role}_gt.json.gz
  ORACLE_SUCCESS:
    SUCCESS_DISTANCE: 3.0

DATASET:
  TYPE: RxR-VLN-CE-v1
  SPLIT: train
  ROLES: [guide]  # "*", "guide", "follower"
  LANGUAGES: [en-US, en-IN]  #  "*", "te-IN", "hi-IN", "en-US", "en-IN"
  DATA_PATH: data/datasets/RxR_VLNCE_v0/{split}/{split}_{role}.json.gz
  SCENES_DIR: data/scene_datasets/
